platform:
  - x86
branches:
  only:
    - master

environment:
  CYG_ROOT: "C:\\cygwin"
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
  OPAM: "%CYG_ROOT%\\home\\appveyor\\.opam"

cache:
  - "%OPAM%"
  - "%CYG_ROOT%\\var\\cache\\setup"

install:
  - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P rsync -P patch -P diffutils -P make -P unzip -P git -P m4 -P perl -P mingw64-x86_64-gcc-core"

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/appveyor-build.sh'"
